sudo: false
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - pip install pep8
    - pip install -r requirements.txt
    - cp travis-ci/manage.py manage.py
script:
    - pep8 rest_router
    - python -m compileall rest_router
    - python manage.py test rest_router
